# Generated by Django 4.2.2 on 2023-07-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='conclusion',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
